=== detixdeti/hsh_bachelor_cs_projects/Web technologies/first HTML experience/ue04/extern.dtd
<!ELEMENT module (Titel, Veranstaltungsart, SWS, Credits, Praesensstunden, Selbststudium, Studiensemester, 
                    empfohlene_Voraussetungen*, Stunden-Pruefungsleistungen+, angestrebte_Lernergebnisse+)>
<!ELEMENT Titel (#PCDATA)>
<!ELEMENT Veranstaltungsart (#PCDATA)>
<!ELEMENT SWS (#PCDATA)>
<!ELEMENT Credits (#PCDATA)>
<!ELEMENT Praesensstunden (#PCDATA)>
<!ELEMENT Selbststudium (#PCDATA)>
<!ELEMENT Studiensemester (#PCDATA)>
<!ELEMENT empfohlene_Voraussetungen (#PCDATA)>
<!ELEMENT Stunden-Pruefungsleistungen (#PCDATA)>
<!ELEMENT angestrebte_Lernergebnisse (#PCDATA)>

=== detixdeti/hsh_bachelor_cs_projects/Web technologies/first HTML experience/ue04/data.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE module SYSTEM "extern.dtd">
<module>
    <Titel>Modul BIN-203/MDI-203 Webtechnologien</Titel>
    <Veranstaltungsart>Vorlesung mit Übung</Veranstaltungsart>
    <SWS>4 SWS</SWS>
    <Credits>6</Credits>
    <Praesensstunden>68 h</Praesensstunden>
    <Selbststudium>112 h</Selbststudium>
    <Studiensemester>4</Studiensemester>

    <empfohlene_Voraussetungen>Programmieren 1-3</empfohlene_Voraussetungen>
    <empfohlene_Voraussetungen>Betriebssysteme und Netze</empfohlene_Voraussetungen>
    <empfohlene_Voraussetungen>Englisch</empfohlene_Voraussetungen>

    <Stunden-Pruefungsleistungen>Prüfung (Klausur oder mündliche Prüfung)</Stunden-Pruefungsleistungen>
    <Stunden-Pruefungsleistungen>experimentelle Arbeit</Stunden-Pruefungsleistungen>

    <angestrebte_Lernergebnisse>Technologische Kompetenz Kennenlernen der grundlegenden Komponenten webbasierter Systeme. Verständnis über das Zusammenspiel dieser
        Komponenten auf Basis verschiedener Protokolle.</angestrebte_Lernergebnisse>
    <angestrebte_Lernergebnisse>Design-Kompetenz Websysteme entwerfen und benutzergerecht gestalten
        können. Auswahl und Anwendung geeigneter Architekturmuster.</angestrebte_Lernergebnisse>
    <angestrebte_Lernergebnisse>Realisierungs-Kompetenz komplexe Websysteme mithilfe aktueller
        Technologien entwickeln und konfigurieren können.</angestrebte_Lernergebnisse>
</module>
